// This is autogenerated file. Do not modify this file!
// File contains compiler flags and other definitions.

#define Foo "Bar"
#define AAA 1234
#define stdc__11 1
#define VARIABLE_1 "VALUE"
#define VARIABLE_2 0
#define Flow123dDebug 1